name: Report Collecting

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '11 * * * *'
    

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore $Env:GITHUB_WORKSPACE/ActionRunner/ActionRunner.csproj
    - name: Build ActionRunner
      run: |
            dotnet build $Env:GITHUB_WORKSPACE/ActionRunner/ActionRunner.csproj
    - name: Retrieve Indonesia Data
      run: |
            dotnet run --project $Env:GITHUB_WORKSPACE/ActionRunner/ActionRunner.csproj
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Instalasi kebutuhan pythoong
      run: |
          python --version
          pip install -r ActionRunner/requirements.txt    
    - name: Plot Indonesia chart
      run: |
          python ActionRunner/createplot.py        
    - name: Commit datasets
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull
        git status
        git add .
        git commit -m "Update Datasets" || echo "Nothing to commit"
        git status
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: erlange/INACOVID
        github_token: ${{ secrets.GITHUB_TOKEN }}          
